version: '3'
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SenhaLonga!123
  flask_app:
    build: 
      context: .
      dockerfile: Dockerfile_python
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - .:/app

